### ISSUE TITLE
Multi "Delete data" feature

### ISSUE THREAD

**Issue by spinecki** [LukeWCS/ext-mgr-plus#1]
Hi, is it possible for you to add multi "Delete data" feature? Your extension allows to multi enable/disable, but after disabling there is a need to delete data... one by one by one, which can take a lot of time. Anyway - this feature still works with this abd extension https://www.phpbb.com/community/viewtopic.php?t=2412821, but it has to be turned with your extension to work (do not know why). Maybe You can use parts of its code. Thanks, Patryk

**Comment by spinecki** [comment]
Sory, github rep is here: https://github.com/javiexin/extension

**Comment by LukeWCS** [comment]
Hi

EMP was primarily developed to be able to quickly and correctly deactivate all extensions when updating phpBB and to be able to reactivate them quickly and correctly after the update. It was also created to be able to quickly and easily create any constellation of active extensions in TBs without having to switch each extension individually, which is cumbersome and time-consuming, especially when developing.

But both the installation (initial activation) of an extension and the uninstallation (delete data) are delicate processes in which a lot can go wrong. For this reason, support for these functions was never planned for EMP and will probably not be implemented in the future either. The effort and the potential for problems are far too high for this.

I do not understand that:
> but it has to be turned with your extension to work (do not know why).

My knowledge of English is modest, it is not my mother tongue. ;)

**Comment by spinecki** [comment]
> I do not understand that:
> 
> > but it has to be turned with your extension to work (do not know why).
> 
> My knowledge of English is modest, it is not my mother tongue. ;)

The other ext works only with your extension turned on and the only functionality that I use from there is multi delete data. Somehow it needs your extension to be turned on. Do not know why. Just a "fun fact".

**Comment by LukeWCS** [comment]
Sorry for the loooong response time, I don't have enough time for my hobbies at the moment.

Interesting, because I didn't know about this extension before you drew my attention to it and I therefore didn't add anything to EMP that could explain this behavior.

I'll close your issue soon since it's not a bug. You will then find our conversation in the new forum area here. I still have to set this up. Until then, this issue will remain.
